### ISSUE TITLE
Build a Molecule master checklist

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-molecule#155]
# Build a Molecule Port Master Checklist

## Design
- [x] **Sim folder and design doc created** (Date: 09/26/2013) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] [Sim suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821) reviewed
  - [x] Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- `N/A` **Learning goals and standards identified** (Date: //)
- `N/A` **Design concept complete**  (Date: //)
- `N/A` **Wireframes complete** (Date: //) 
- `N/A` **Mockups complete** (Date: //) 
 - `N/A` Mockups checked for colorblind and greyscale
- `N/A`  **Features for PhET-iO discussion** 
- `N/A`  **Interviews complete** (Date: //) 
    - Results reported to team
    - Notes pasted into design doc
    - Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Sim primer draft - #241 
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items** 
  - [x] Share new features, design challenges, and treats with group!
  - [x] Review legacy gold star activities, copy over if appropriate
  - [x] Email announcement language
  - `N/A` Add to Edmodo
  - `N/A` Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) - #241 
  - `N/A` Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 07/18/20)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 05/01/19)
- [x] **Sim is "feature complete"** (Date: 06/19/20) 
- [x] **Code review completed** (Date: 06/01/20) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
- [x] **Published** (Date: 10/13/20) 
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 02/12/19) 
- [x] **Dev testing complete** (Date: 06/17/20) 
- [x] **First RC published** (Date: 06/19/20)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 10/12/20)
